In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [9]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'train.csv' # TODO: download train data and supply path here 
y, x, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
from implementations import *
from cross_validation import *

In [44]:
def build_poly(x, degree):
    """polynomial basis functions for input data x, for j=0 up to j=degree."""
    poly=np.ones(len(x))
    for deg in range(1,degree+1):
        poly = np.c_[poly,np.power(x,deg)]
    return poly

In [77]:
gamma=np.logspace(-3, 0, 2)
print(gamma)

[0.001 1.   ]


In [72]:
a=np.array([1,2,3])
b=-999
b.type

AttributeError: 'int' object has no attribute 'type'

In [96]:
x[:,0][x[:,0]==999]

array([], dtype=float64)

In [89]:
x[:,0][x[:,0]==-999]=np.mean(x[:,0][x[:,0]>-999])

In [90]:
x[:,0][x[:,0]==np.mean(x[:,0][x[:,0]>-999])]

array([], dtype=float64)

In [99]:
mean = np.mean(x[:,0][x[:,0]>-999])
x[:,0][x[:,0]==-999] = mean
new_mean=np.mean(x[:,0])
x[:,0] = x[:,0] - new_mean
std_x = np.std(x[:,0])
x[:,0] = x[:,0] / std_x

In [100]:
x[0,0]

0.3149106559622163

In [104]:
x[np.argmin(x[:,0]),0]

-2.1386724726641186

In [114]:
x[0,29]

113.497

In [119]:
month = 8;
switch (month) {
            case 1:  monthString = "January";
                     break;
            case 2:  monthString = "February";
                     break;
            case 3:  monthString = "March";
                     break;
            case 4:  monthString = "April";
                     break;
            case 5:  monthString = "May";
                     break;
            case 6:  monthString = "June";
                     break;
            case 7:  monthString = "July";
                     break;
            case 8:  monthString = "August";
                     break;
            case 9:  monthString = "September";
                     break;
            case 10: monthString = "October";
                     break;
            case 11: monthString = "November";
                     break;
            case 12: monthString = "December";
                     break;
            default: monthString = "Invalid month";
                     break;}
print(monthString)

SyntaxError: invalid syntax (<ipython-input-119-b65453c88645>, line 2)

In [121]:
a='re'
if a=='re':
    print('youpi')

youpi


In [126]:
a = False

In [127]:
if a:
    print(1)

In [129]:
for d in range (1,8):
    print(d)

1
2
3
4
5
6
7


In [132]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [134]:
method = 'GD'
if method != 'GD' or method != 'SGD':
        raise SyntaxWarning

SyntaxWarning: 

In [9]:
y=np.array([1,1])
x=np.array([[1,1],[1,1]])

In [10]:
w=compute_gradient(y,x,y)

In [11]:
print(w)

[1. 1.]


In [16]:
test='b'
if (test != 'a' and test != 'b'):
    print(1)

In [19]:
a=np.array([1,2,3])

In [5]:
print(x.shape)

(250000, 30)


In [11]:
a=np.random.randint(0,x.shape[0])

In [12]:
print(a)

40826


In [15]:
print(x[a,:])

[ 2.02665e+02  1.87570e+01  1.68327e+02  2.16677e+02 -9.99000e+02
 -9.99000e+02 -9.99000e+02  2.49600e+00  2.80300e+00  4.40549e+02
  1.01490e+01  1.28500e+00 -9.99000e+02  2.00740e+01  1.55000e+00
 -1.86900e+00  2.03724e+02 -3.49000e-01 -2.48000e-01  1.33980e+01
 -6.09000e-01  5.29726e+02  1.00000e+00  2.16751e+02  7.02000e-01
  2.79200e+00 -9.99000e+02 -9.99000e+02 -9.99000e+02  2.16751e+02]


In [6]:
x=np.array([1,2,3,-999])
print(x[x>-999])
print(mean)

[1 2 3]
2.0


In [7]:
x[x==-999] = mean

In [8]:
print(x)

[1 2 3 2]


In [11]:
print(x[:,1].shape)

(250000,)


In [12]:
def build_poly(x, degree):
    """polynomial basis functions for input data x"""
    tx = x
    for i in range(2, degree + 1):
        power = np.apply_along_axis(lambda c: c**i, 1 , x)
        tx = np.concatenate((tx, power), axis=1)
    return tx

In [18]:
a=np.array([[2,3,4],[1,2,3]])

In [19]:
print(build_poly(a,3))

[[ 2  3  4  4  9 16  8 27 64]
 [ 1  2  3  1  4  9  1  8 27]]


In [35]:
def build_poly(x, degree):
    """Polynomial basis functions for input data x, for j=0 up to j=degree."""
    poly=x
    for deg in range(2,degree+1):
        poly = np.c_[poly,np.power(x,deg)]
    return poly

In [37]:
a=np.array([[1,2,3]])
print(build_poly(a,1))

[[1 2 3]]
